import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class submit{

    private JPanel paan;
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JButton submit;
    private JComboBox state;
    private JComboBox district;
    private JTextField taluka;

    //static Hellochk m=  new Hellochk();

    String[] distr={"District"};
    String [] Andra={"<District>",    "Adilabad",
            "Anantapur",
            "Chittoor",
            "Kakinada",
            "Guntur",
            "Hyderabad",
            "Karimnagar",
            "Khammam",
            "Krishna",
            "Kurnool",
            "Mahbubnagar",
            "Medak",
            "Nalgonda",
            "Nizamabad",
            "Ongole",
            "Hyderabad",
            "Srikakulam",
            "Nellore",
            "Visakhapatnam",
            "Vizianagaram",
            "Warangal",
            "Eluru",
            "Kadapa"};

    String[] Aru={"<District>","Anjaw",
            "Changlang",
            "East Siang",
            "Kurung Kumey",
            "Lohit",
            "Lower Dibang Valley",
            "Lower Subansiri",
            "Papum Pare",
            "Tawang",
            "Tirap",
            "Dibang Valley",
            "Upper Siang",
            "Upper Subansiri",
            "West Kameng",
            "West Siang"};

    String[] Assam={"<District>","Baksa",
            "Barpeta",
            "Bongaigaon",
            "Cachar",
            "Chirang",
            "Darrang",
            "Dhemaji",
            "Dima Hasao",
            "Dhubri",
            "Dibrugarh",
            "Goalpara",
            "Golaghat",
            "Hailakandi",
            "Jorhat",
            "Kamrup",
            "Kamrup Metropolitan",
            "Karbi Anglong",
            "Karimganj",
            "Kokrajhar",
            "Lakhimpur",
            "Marigaon",
            "Nagaon",
            "Nalbari",
            "Sibsagar",
            "Sonitpur",
            "Tinsukia",
            "Udalguri"};

    String[] Bihar={"<District>","Araria",
            "Arwal",
            "Aurangabad",
            "Banka",
            "Begusarai",
            "Bhagalpur",
            "Bhojpur",
            "Buxar",
            "Darbhanga",
            "East Champaran",
            "Gaya",
            "Gopalganj",
            "Jamui",
            "Jehanabad",
            "Kaimur",
            "Katihar",
            "Khagaria",
            "Kishanganj",
            "Lakhisarai",
            "Madhepura",
            "Madhubani",
            "Munger",
            "Muzaffarpur",
            "Nalanda",
            "Nawada",
            "Patna",
            "Purnia",
            "Rohtas",
            "Saharsa",
            "Samastipur",
            "Saran",
            "Sheikhpura",
            "Sheohar",
            "Sitamarhi",
            "Siwan",
            "Supaul",
            "Vaishali",
            "West Champaran",
            "Chandigarh"};

    String[] Chatt={"<District>","Araria",
            "Arwal",
            "Aurangabad",
            "Banka",
            "Begusarai",
            "Bhagalpur",
            "Bhojpur",
            "Buxar",
            "Darbhanga",
            "East Champaran",
            "Gaya",
            "Gopalganj",
            "Jamui",
            "Jehanabad",
            "Kaimur",
            "Katihar",
            "Khagaria",
            "Kishanganj",
            "Lakhisarai",
            "Madhepura",
            "Madhubani",
            "Munger",
            "Muzaffarpur",
            "Nalanda",
            "Nawada",
            "Patna",
            "Purnia",
            "Rohtas",
            "Saharsa",
            "Samastipur",
            "Saran",
            "Sheikhpura",
            "Sheohar",
            "Sitamarhi",
            "Siwan",
            "Supaul",
            "Vaishali",
            "West Champaran",
            "Chandigarh"};

    String[] gj={"<District>","Ahmedabad",
            "Amreli district",
            "Anand",
            "Banaskantha",
            "Bharuch",
            "Bhavnagar",
            "Dahod",
            "The Dangs",
            "Gandhinagar",
            "Jamnagar",
            "Junagadh",
            "Kutch",
            "Kheda",
            "Mehsana",
            "Narmada",
            "Navsari",
            "Patan",
            "Panchmahal",
            "Porbandar",
            "Rajkot",
            "Sabarkantha",
            "Surendranagar",
            "Surat",
            "Vyara",
            "Vadodara",
            "Valsad"};
    String[] Goa={"<District>","North Goa","South Goa"};
    String[] Har={"<District>","Ambala",
            "Bhiwani",
            "Faridabad",
            "Fatehabad",
            "Gurgaon",
            "Hissar",
            "Jhajjar",
            "Jind",
            "Karnal",
            "Kaithal",
            "Kurukshetra",
            "Mahendragarh",
            "Mewat",
            "Palwal",
            "Panchkula",
            "Panipat",
            "Rewari",
            "Rohtak",
            "Sirsa",
            "Sonipat",
            "Yamuna Nagar"};
    String[] Hima={"<District>","Bilaspur",
            "Chamba",
            "Hamirpur",
            "Kangra",
            "Kinnaur",
            "Kullu",
            "Lahaul and Spiti",
            "Mandi",
            "Shimla",
            "Sirmaur",
            "Solan",
            "Una",};
    String[] jk={"<District>","Anantnag",
            "Badgam",
            "Bandipora",
            "Baramulla",
            "Doda",
            "Ganderbal",
            "Jammu",
            "Kargil",
            "Kathua",
            "Kishtwar",
            "Kupwara",
            "Kulgam",
            "Leh",
            "Poonch",
            "Pulwama",
            "Rajauri",
            "Ramban",
            "Reasi",
            "Samba",
            "Shopian",
            "Srinagar",
            "Udhampur"};
    String[] jh={"<District>","Bokaro",
            "Chatra",
            "Deoghar",
            "Dhanbad",
            "Dumka",
            "East Singhbhum",
            "Garhwa",
            "Giridih",
            "Godda",
            "Gumla",
            "Hazaribag",
            "Jamtara",
            "Khunti",
            "Koderma",
            "Latehar",
            "Lohardaga",
            "Pakur",
            "Palamu",
            "Ramgarh",
            "Ranchi",
            "Sahibganj",
            "Seraikela Kharsawan",
            "Simdega",
            "West Singhbhum"};
    String[] ka={"<District>","Bagalkot",
            "Bangalore Rural",
            "Bangalore Urban",
            "Belgaum",
            "Bellary",
            "Bidar",
            "Bijapur",
            "Chamarajnagar",
            "Chikkamagaluru",
            "Chikkaballapur",
            "Chitradurga",
            "Davanagere",
            "Dharwad",
            "Dakshina Kannada",
            "Gadag",
            "Gulbarga",
            "Hassan",
            "Haveri district",
            "Kodagu",
            "Kolar",
            "Koppal",
            "Mandya",
            "Mysore",
            "Raichur",
            "Shimoga",
            "Tumkur",
            "Udupi",
            "Uttara Kannada",
            "Ramanagara",
            "Yadgir"};
    String[] kerla={"<District>","Alappuzha",
            "Ernakulam",
            "Idukki",
            "Kannur",
            "Kasaragod",
            "Kollam",
            "Kottayam",
            "Kozhikode",
            "Malappuram",
            "Palakkad",
            "Pathanamthitta",
            "Thrissur",
            "Thiruvananthapuram",
            "Wayanad"};
    String[] mp={"<District>","Alirajpur",
            "Anuppur",
            "Ashok Nagar",
            "Balaghat",
            "Barwani",
            "Betul",
            "Bhind",
            "Bhopal",
            "Burhanpur",
            "Chhatarpur",
            "Chhindwara",
            "Damoh",
            "Datia",
            "Dewas",
            "Dhar",
            "Dindori",
            "Guna",
            "Gwalior",
            "Harda",
            "Hoshangabad",
            "Indore",
            "Jabalpur",
            "Jhabua",
            "Katni",
            "Khandwa (East Nimar)",
            "Khargone (West Nimar)",
            "Mandla",
            "Mandsaur",
            "Morena",
            "Narsinghpur",
            "Neemuch",
            "Panna",
            "Rewa",
            "Rajgarh",
            "Ratlam",
            "Raisen",
            "Sagar",
            "Satna",
            "Sehore",
            "Seoni",
            "Shahdol",
            "Shajapur",
            "Sheopur",
            "Shivpuri",
            "Sidhi",
            "Singrauli",
            "Tikamgarh",
            "Ujjain",
            "Umaria",
            "Vidisha"};
    String[] mh={"<District>","Ahmednagar",
            "Akola",
            "Amravati",
            "Aurangabad",
            "Bhandara",
            "Beed",
            "Buldhana",
            "Chandrapur",
            "Dhule",
            "Gadchiroli",
            "Gondia",
            "Hingoli",
            "Jalgaon",
            "Jalna",
            "Kolhapur",
            "Latur",
            "Mumbai City",
            "Mumbai suburban",
            "Nandurbar",
            "Nanded",
            "Nagpur",
            "Nashik",
            "Osmanabad",
            "Parbhani",
            "Pune",
            "Raigad",
            "Ratnagiri",
            "Sindhudurg",
            "Sangli",
            "Solapur",
            "Satara",
            "Thane",
            "Wardha",
            "Washim",
            "Yavatmal"};
    String[] mn={"<District>","Bishnupur",
            "Churachandpur",
            "Chandel",
            "Imphal East",
            "Senapati",
            "Tamenglong",
            "Thoubal",
            "Ukhrul",
            "Imphal West"};
    String[] ml={"<District>","East Garo Hills",
            "East Khasi Hills",
            "Jaintia Hills",
            "Ri Bhoi",
            "South Garo Hills",
            "West Garo Hills",
            "West Khasi Hills"};
    String[] mz={"<District>","Aizawl",
            "Champhai",
            "Kolasib",
            "Lawngtlai",
            "Lunglei",
            "Mamit",
            "Saiha",
            "Serchhip"};
    String[] nl={"<District>","Dimapur",
            "Kohima",
            "Mokokchung",
            "Mon",
            "Phek",
            "Tuensang",
            "Wokha",
            "Zunheboto"};
    String[] or={"<District>","Angul",
            "Boudh (Bauda)",
            "Bhadrak",
            "Balangir",
            "Bargarh (Baragarh)",
            "Balasore",
            "Cuttack",
            "Debagarh (Deogarh)",
            "Dhenkanal",
            "Ganjam",
            "Gajapati",
            "Jharsuguda",
            "Jajpur",
            "Jagatsinghpur",
            "Khordha",
            "Kendujhar (Keonjhar)",
            "Kalahandi",
            "Kandhamal",
            "Koraput",
            "Kendrapara",
            "Malkangiri",
            "Mayurbhanj",
            "Nabarangpur",
            "Nuapada",
            "Nayagarh",
            "Puri",
            "Rayagada",
            "Sambalpur",
            "Subarnapur (Sonepur)",
            "Sundergarh"};
    String[] pb={"<District>","Amritsar",
            "Barnala",
            "Bathinda",
            "Firozpur",
            "Faridkot",
            "Fatehgarh Sahib",
            "Fazilka",
            "Gurdaspur",
            "Hoshiarpur",
            "Jalandhar",
            "Kapurthala",
            "Ludhiana",
            "Mansa",
            "Moga",
            "Sri Muktsar Sahib",
            "Pathankot",
            "Patiala",
            "Rupnagar",
            "Ajitgarh (Mohali)",
            "Sangrur",
            "Nawanshahr",
            "Tarn Taran",};
    String[] rj={"<District>","Ajmer",
            "Alwar",
            "Bikaner",
            "Barmer",
            "Banswara",
            "Bharatpur",
            "Baran",
            "Bundi",
            "Bhilwara",
            "Churu",
            "Chittorgarh",
            "Dausa",
            "Dholpur",
            "Dungapur",
            "Ganganagar",
            "Hanumangarh",
            "Jhunjhunu",
            "Jalore",
            "Jodhpur",
            "Jaipur",
            "Jaisalmer",
            "Jhalawar",
            "Karauli",
            "Kota",
            "Nagaur",
            "Pali",
            "Pratapgarh",
            "Rajsamand",
            "Sikar",
            "Sawai Madhopur",
            "Sirohi",
            "Tonk",
            "Udaipur"};
    String[] sk={"<District>","East Sikkim",
            "North Sikkim",
            "South Sikkim",
            "West Sikkim"};
    String[] tn={"<District>","Ariyalur",
            "Chennai",
            "Coimbatore",
            "Cuddalore",
            "Dharmapuri",
            "Dindigul",
            "Erode",
            "Kanchipuram",
            "Kanyakumari",
            "Karur",
            "Madurai",
            "Nagapattinam",
            "Nilgiris",
            "Namakkal",
            "Perambalur",
            "Pudukkottai",
            "Ramanathapuram",
            "Salem",
            "Sivaganga",
            "Tirupur",
            "Tiruchirappalli",
            "Theni",
            "Tirunelveli",
            "Thanjavur",
            "Thoothukudi",
            "Tiruvallur",
            "Tiruvarur",
            "Tiruvannamalai",
            "Vellore",
            "Viluppuram",
            "Virudhunagar"};
    String[] tr={"<District>","Dhalai",
            "North Tripura",
            "South Tripura",
            "Khowai",
            "West Tripura"};
    String[] telan={"<District>","Adilabad","Bhadradri Kothagudem","Hyderabad","Jagtial",
            "Jangaon",
            "Jayashankar Bhoopalpally",
            "Jogulamba Gadwal",
            "Kamareddy",
            "Karimnagar",
            "Khammam",
            "Komaram Bheem Asifabad",
            "Mahabubabad",
            "Mahabubnagar",
            "Mancherial",
            "Medak",
            "Medchal",
            "Nagarkurnool",
            "Nalgonda",
            "Nirmal",
            "Nizamabad",
            "Peddapalli",
            "Rajanna Sircilla",
            "Rangareddy",
            "Sangareddy",
            "Siddipet",
            "Suryapet",
            "Vikarabad",
            "Wanaparthy",
            "Warangal",
            "Yadadri Bhuvangiri"
    };
    String[] uk={"<Disrtict>","Almora",
            "Bageshwar",
            "Chamoli",
            "Champawat",
            "Dehradun",
            "Haridwar",
            "Nainital",
            "Pauri Garhwal",
            "Pithoragarh",
            "Rudraprayag",
            "Tehri Garhwal",
            "Udham Singh Nagar",
            "Uttarkashi"};
    String[] sup ={"<District>","Agra",
            "Allahabad",
            "Aligarh",
            "Ambedkar Nagar",
            "Auraiya",
            "Azamgarh",
            "Barabanki",
            "Budaun",
            "Bagpat",
            "Bahraich",
            "Bijnor",
            "Ballia",
            "Banda",
            "Balrampur",
            "Bareilly",
            "Basti",
            "Bulandshahr",
            "Chandauli",
            "Chhatrapati Shahuji Maharaj Nagar",
            "Chitrakoot",
            "Deoria",
            "Etah",
            "Kanshi Ram Nagar",
            "Etawah",
            "Firozabad",
            "Farrukhabad",
            "Fatehpur",
            "Faizabad",
            "Gautam Buddh Nagar",
            "Gonda",
            "Ghazipur",
            "Gorakhpur",
            "Ghaziabad",
            "Hamirpur",
            "Hardoi",
            "Mahamaya Nagar",
            "Jhansi",
            "Jalaun",
            "Jyotiba Phule Nagar",
            "Jaunpur district",
            "Ramabai Nagar (Kanpur Dehat)",
            "Kannauj",
            "Kanpur",
            "Kaushambi",
            "Kushinagar",
            "Lalitpur",
            "Lakhimpur Kheri",
            "Lucknow",
            "Mau",
            "Meerut",
            "Maharajganj",
            "Mahoba",
            "Mirzapur",
            "Moradabad",
            "Mainpuri",
            "Mathura",
            "Muzaffarnagar",
            "Panchsheel Nagar district (Hapur)",
            "Pilibhit",
            "Shamli",
            "Pratapgarh",
            "Rampur",
            "Raebareli",
            "Saharanpur",
            "Sitapur",
            "Shahjahanpur",
            "Sant Kabir Nagar",
            "Siddharthnagar",
            "Sonbhadra",
            "Sant Ravidas Nagar",
            "Sultanpur",
            "Shravasti",
            "Unnao",
            "Varanasi"};
    String[] wb={"<District>","Birbhum",
            "Bankura",
            "Bardhaman",
            "Darjeeling",
            "Dakshin Dinajpur",
            "Hooghly",
            "Howrah",
            "Jalpaiguri",
            "Cooch Behar",
            "Kolkata",
            "Maldah",
            "Paschim Medinipur",
            "Purba Medinipur",
            "Murshidabad",
            "Nadia",
            "North 24 Parganas",
            "South 24 Parganas",
            "Purulia",
            "Uttar Dinajpur"};
    String[][] stdr={distr,Andra,Aru,Assam,Bihar,Chatt,Goa,gj,Har,Hima,jk,jh,ka,kerla,mp,mh,mn,ml,mz,nl,or,pb,rj,sk,tn,telan,tr,uk, sup,wb};
    public submit() {
       district.setVisible(false);


        state.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                district.removeAllItems();
                district.setVisible(true);

                if (state.getSelectedIndex() != 0) {
                    System.out.println("Selected State is " + state.getItemAt(state.getSelectedIndex()));

                    for(String i : stdr[state.getSelectedIndex()]){
                        district.addItem(i);
                    }
                }
            }
        });
    }

    public void subm() {
        JFrame frm = new JFrame("FindErr");
        JMenuBar mb= new JMenuBar();
        JMenuItem abt=new JMenuItem("About");
        JMenu fl=new JMenu("File");
        fl.add(abt);
        mb.add(fl);
        JMenuItem so=new JMenuItem("Sign out");
        JMenu act=new JMenu("Account");
        act.add(so);
        mb.add(act);

        frm.getContentPane().add(BorderLayout.NORTH,mb);

        abt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new About();
            }
        });

        so.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Hellochk hk=new Hellochk();
                hk.Hello();
                frm.dispose();
            }
        });

        Image icon= Toolkit.getDefaultToolkit().getImage("D:\\project_sy\\Prototype2\\iconn.jpeg");
        frm.setIconImage(icon);
        frm.setSize(600, 200);
        frm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frm.add(paan);
        frm.setVisible(true);
        String[] s = {"<state>","Andhra Pradesh",
                "Arunachal Pradesh",
                "Assam",
                "Bihar",
                "Chhattisgarh",
                "Goa",
                "Gujarat",
                "Haryana",
                "Himachal Pradesh",
                "Jammu and Kashmir",
                "Jharkhand",
                "Karnataka",
                "Kerala",
                "Madhya Pradesh",
                "Maharashtra",
                "Manipur",
                "Meghalaya",
                "Mizoram",
                "Nagaland",
                "Odisha",
                "Punjab",
                "Rajasthan",
                "Sikkim",
                "Tamil Nadu",
                "Telangana",
                "Tripura",
                "Uttarakhand",
                "Uttar Pradesh",
                "West Bengal",
               };
        for( String i: s){
            state.addItem(i);
        }
        submit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (state.getSelectedIndex() != 0) {
                    System.out.println("Selected State is " + state.getItemAt(state.getSelectedIndex()));
                }
                if(district.getSelectedIndex()!=0){
                    System.out.println("Selected District is :"+ district.getItemAt(district.getSelectedIndex()));
                }

                new Aboutur();
                frm.dispose();
            }
        });

    }

    public static void main(String[] args){
        submit sb=new submit();
        sb.subm();

    }



}
